spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql://localhost:3306/travelshare?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #    schema:
    #      - classpath:department.sql
    #      - classpath:employee.sql
    initialization-mode: always

server:
  port: 8081

mybatis:
  type-aliases-package: com.nbcj.springboot.domain
  mapper-locations: classpath:mapper/*.xml
